MvcBacklist/MvcBacklist/Controllers/BooksController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MvcBacklist.Models;
using MvcBacklist.Models.Parameters;

namespace MvcBacklist.Controllers
{
    public class BooksController : Controller
    {
        private readonly BackListDbContext _db = new BackListDbContext();

        // GET: Books
        public ActionResult Index()
        {
            return View(_db.Books.ToList());
        }
        //public ActionResult LoadData()
        //{
        //    var mapper = new DbMapper();
        //    var data = mapper.Map(_db.Books);
        //    var s =  Json(new {data}, JsonRequestBehavior.AllowGet);
        //    return s;
        //}

        public JsonResult LoadData(DtParameterModel model)
        {
            var mapper = new DbMapper();
            var data = mapper.Map(_db.Books);
            var json = Json(new
            {
                iTotalRecords = model.Length,
                iTotalDisplayRecords = model.Length,
                aaData = data
            },
                JsonRequestBehavior.AllowGet);
            return json;
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var book = _db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return PartialView(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.Authors = new MultiSelectList(_db.Authors, "AuthorId", "Name");
            return View();
        }

        // POST: Books/Create
        [HttpPost]
        public ActionResult Create(Book book, int[] authors)
        {
            if (authors != null)
            {
                foreach (var authorId in authors)
                {
                    var author = _db.Authors.Find(authorId);
                    book.Authors.Add(author);
                }
            }
            _db.Books.Add(book);
            _db.SaveChanges();
            return View("Index", _db.Books);
        }


        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Title,ReleaseDate,Rating,NumberOfPages")] Book book)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Books.Add(book);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(book);
        //}

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,ReleaseDate,Rating,NumberOfPages")] Book book)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(book).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = _db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = _db.Books.Find(id);
            _db.Books.Remove(book);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcBacklist/MvcBacklist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Backlist Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Backlist Application", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Books", "Index", "Books")</li>
                    <li>@Html.ActionLink("Authors", "Index", "Authors")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>