Employee Accounting/EmployeeAccWebProj/EmployeeAccWebProj/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BusinessLogic;
using BusinessLogic.Entity;
using BusinessLogic.Paging;
using BusinessLogic.ViewModel;

namespace EmployeeAccWebProj.Controllers
{
    public class EmployeesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Returns Json data with Employees 
        /// </summary>
        /// <param name="model">Object that represents datatable paging settings</param>
        /// <returns></returns>
        public JsonResult LoadData(DataTableAjaxPostModel model)
        {
            if (model.search == null)
            {
                model.search = new Search { value = "" };
            }
            int totalRecords;
            int recordsFiltered;

            var employees = new EmployeeRepository().GetPaginated(model, out totalRecords, out recordsFiltered);
            return Json(new
            {
                draw = model.draw,
                recordsTotal = totalRecords,
                recordsFiltered = recordsFiltered,
                data = employees

            }, JsonRequestBehavior.AllowGet);
        }

        private static IEnumerable<DepartmentEntity> DepartmentsGetData()
        {
            List<DepartmentEntity> department;
            using (var departmentService = new DepartmentService())
            {
                department = departmentService.GetData();
            }
            return department;
        }
        /// <summary>
        /// Returns empty Create form using Get method
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            PopulateDepartmentsDropDownList();
            return PartialView();
        }

        /// <summary>
        /// Saves new employee to database using Post method
        /// </summary>
        /// <param name="employee">Employee view model object</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,DeptId,DeptName")] EmployeeViewModel employee)
        {

            using (var employeeService = new EmployeeService())
            {
                if (!ModelState.IsValid)
                {
                    PopulateDepartmentsDropDownList();
                    return HttpNotFound();
                }
                employeeService.Create(employee);
                return Json("");
            }
        }

        /// <summary>
        /// Returns Edit form with employee data using Get method
        /// </summary>
        /// <param name="id">Int id of record to edit</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var departments = DepartmentsGetData();
            List<EmployeeViewModel> data;
            using (var employeeService = new EmployeeService())
            {
                var employees = employeeService.GetData();
                data = employeeService.LoadEntity(employees, departments);
            }

            var employee = data.Find(a => a.EmployeeId == id);

            if (employee == null)
            {
                return HttpNotFound();
            }
            PopulateDepartmentsDropDownList(employee.EmployeeId);
            return PartialView(employee);
        }

        /// <summary>
        ///  Saves edited employee to database using Post method
        /// </summary>
        /// <param name="employee">Employee view model object</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,FirstName,LastName,DeptId,DeptName,LastModifiedAt")] EmployeeViewModel employee)
        {
            using (var employeeService = new EmployeeService())
            {
                if (ModelState.IsValid)
                {

                    employeeService.Edit(employee);
                    return RedirectToAction("Index");
                }

                PopulateDepartmentsDropDownList(employee.EmployeeId);
                return PartialView(employee);
            }
        }

        /// <summary>
        /// Returns Delete form with employee data using Get method
        /// </summary>
        /// <param name="id">Int id of record to delete</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var departments = DepartmentsGetData();
            using (var employeeService = new EmployeeService())
            {
                var employees = employeeService.GetData();
                var data = employeeService.LoadEntity(employees, departments);
                var employee = data.First(x => x.EmployeeId == id);
                if (employee == null)
                {
                    return HttpNotFound();
                }
                return PartialView(employee);
            }
        }

        /// <summary>
        /// Deletes record from database by id
        /// </summary>
        /// <param name="id">Int id of record to delete</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var employeeService = new EmployeeService())
            {
                employeeService.Delete(id);
                return RedirectToAction("Index");
            }
        }

        private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
        {
            var data = DepartmentsGetData();
            ViewBag.DeptID = new SelectList(data, "DepartmentID", "Name", selectedDepartment);
        }
    }
}

Employee Accounting/EmployeeAccWebProj/EmployeeAccWebProj/Views/Employees/Create.cshtml
@model BusinessLogic.ViewModel.EmployeeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Ajax.BeginForm("Create", "Employees", null,
    new AjaxOptions
    {
        OnSuccess = "crudNamespace.onCreateFormHide()"
    }, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.DeptId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DeptId, null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.DeptId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick=crudNamespace.onFormSubmit() class="btn btn-default" />
                <input type="button" value="Cancel" onclick=crudNamespace.onCreateFormHide()  class="btn btn-default">
            </div>
        </div>
        
        
        
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            </div>
        </div>
        <hr />
    </div>
}

Employee Accounting/EmployeeAccWebProj/EmployeeAccWebProj/Views/Employees/Delete.cshtml
@model BusinessLogic.ViewModel.EmployeeViewModel

@{
    ViewBag.Title = "Delete";
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new {@id = "DeleteEmployeeForm"}))
{
    @Html.AntiForgeryToken()

    <div class="dl-horizontal">
        <dl>
            <dt>
                @Html.HiddenFor(model => model.EmployeeId)
            </dt>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DeptName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DeptName)
            </dd>
        </dl>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Delete" onclick=crudNamespace.deleteEmployee() class="btn btn-default">
                    <input type="button" value="Cancel" onclick=crudNamespace.onDeleteFormHide() class="btn btn-default">
                </div>
            </div>
        </div>
        <hr />
    </div>
}

Employee Accounting/EmployeeAccWebProj/EmployeeAccWebProj/Views/Employees/Edit.cshtml
@model BusinessLogic.ViewModel.EmployeeViewModel

@Html.ValidationSummary(true)

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new {@id = "EditEmployeeForm"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" id="">

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.EmployeeId)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeptId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DeptId, null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.DeptId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" onclick=crudNamespace.editEmployee() class="btn btn-default">
                <input type="button" value="Cancel" onclick=crudNamespace.onEditFormHide() class="btn btn-default">
            </div>
        </div>
        <hr />
    </div>
}

Employee Accounting/EmployeeAccWebProj/EmployeeAccWebProj/Views/Employees/Index.cshtml
<div class='page-header'>
    <div class='btn-toolbar pull-right'>
        <div class='btn-group'>
            <button type='button' class='btn btn-primary' onclick=crudNamespace.showCreateForm()>New Employee</button>
        </div>
    </div>
    <h2>Employee list</h2>
</div>

<div id="EditEmployeeDiv" style="display:none"></div>
<div id="DeleteEmployeeDiv" style="display:none"></div>
<div id="CreateEmployeeDiv" style="display:none"></div>

<div class="table-responsive">
    <table id="emplTable" class='table dt-responsive'>
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Department Id</th>
                <th>Department Name</th>
                <th>Last Modified At</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
    </table>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog">

    <div class="modal-dialog vertical-align-center">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>

                </button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>

            </div>
            <div class="modal-body">...</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>











<style>
    tr.even {
        background-color: #F5F5F5 !important;
    }
</style>
@* Load datatable css *@
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="//cdn.datatables.net/responsive/2.2.0/css/responsive.bootstrap.min.css" rel="stylesheet" />
      @* load datatable js *@
@section Scripts{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.0/js/responsive.bootstrap.min.js"></script>
}